[package]
name = "rust-example"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["miniqueue", "trader"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
